config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invites
  resources :info_logs
  resources :lost_items
  get 'peliluola', as: 'afterparty', action: 'index', controller: 'afterparty'
  post 'peliluola/signup', as: 'signup_afterparty', controller: 'afterparty', action: 'signup'

  resources :contacts do
    collection do
      get 'export'
    end
  end

  resources :users do
    collection do
      get 'mailinglists'
    end
    member do
      get 'photo'
      post 'toggle_event'
    end
  end

  get "sessions/create", as: "login"
  post "sessions/auth", as: "auth"
  get "sessions/logout", as: "logout"
  post "sessions/logout"
  get 'oidc/authenticator/callback', to: 'sessions#sso'

  # a-umlaut in querystring just fails...
  get "friendtickets/conflulist"
  # so putting it in path works...
  get "friendtickets/conflulist/:cn", controller: 'friendtickets', action: 'conflulist'

  get "friendtickets/search", as: "search_friendtickets"
  post "friendtickets/search"

  get "friendtickets/own"
  post "friendtickets/own"

  get "friendtickets/edit"
  patch "friendtickets/:id", controller: 'friendtickets', as: 'friendticket', action: 'update'

  get "friendtickets/stats"

  resources :events do
    member do
      get 'stats'
      get 'organizers'
      get 'allergies'
    end
  end

  root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

require 'codegen'

class User < ApplicationRecord
  has_many :eventparticipations, dependent: :destroy
  has_many :eventparticipationmetum, dependent: :destroy
  has_many :events, through: :eventparticipations
  has_many :friendtickets, dependent: :destroy
  has_many :pmscodes, dependent: :destroy
  has_many :invites_created, dependent: :destroy, foreign_key: :createdby, class_name: 'Invite'
  has_many :invites_used, dependent: :destroy, foreign_key: :usedby, class_name: 'Invite'

  scope :active, -> { where(state: 1) }
  scope :nophoto, -> { select(User.column_names.map(&:to_sym) - [:photo]) }

  def <=>(other)
    displayname.downcase <=> other.displayname.downcase
  end

  def self.states
    %w[NotInLDAP Active Disabled]
  end

  def disabled?
    !state || state == 0 || state == 2
  end

  def in_ldap(found)
    return if disabled?

    self.state = found ? 1 : 0
  end

  def disable
    self.state = 2
    self.email += "-disabled"
    del_group 'confluence-users'
  end

  def enable
    self.state = 1
    self.email = email.gsub(/-disabled$/, '')
    add_group 'confluence-users'
  end

  def to_s
    displayname
  end

  def cn
    dn.split(",")[0][3..]
  end

  def eventorg?
    events.map(&:code).include? CURRENT_EVENT
  end

  def admin?
    in_group? 'people-manager'
  end

  def in_group?(grp)
    groups.include?(grp)
  end

  def del_group(grp)
    tmp = groups.split(';')
    tmp.delete grp
    self.groups = tmp.join(';')
  end

  def add_group(grp)
    tmp = groups.split(';')
    tmp << grp
    self.groups = tmp.join(';')
  end

  def access_friendtickets?
    in_group?('infocrew') || admin?
  end

  def access_infolog?
    in_group?('infolog') || admin?
  end

  def lastevent
    events.sort.reverse.each do |ev|
      next if ev.afterparty?

      return ev.shortname
    end
    ''
  end

  def allevents
    events.map(&:shortname).compact_blank.join(", ")
  end

  def in_current_event?
    events.map(&:id).include? CURRENT_EVENT_ID
  end

  def get_meta(event)
    meta = {}
    eventparticipationmetum.where(event_id: event.id, user_id: id).find_each do |m|
      meta[m.key] = JSON.parse(m.value)
    end
    meta
  end

  def set_meta(event, metas)
    update_meta(event, metas)
    eventparticipationmetum.where(event_id: event.id, user_id: id).where.not(key: metas.keys).destroy_all
  end

  def update_meta(event, metas)
    metas.each do |key, value|
      m = eventparticipationmetum.where(event_id: event.id, user_id: id, key:).first_or_create
      m.value = value.to_json
      m.save
    end
  end

  def namelink
    styledname = ERB::Util.html_escape_once displayname
    if disabled?
      styledname = "<i class='bi bi-x-lg' style='color: red' ></i> <span class='text-decoration-line-through'>#{styledname}</span>"
    end
    ActionController::Base.helpers.link_to ActionController::Base.helpers.raw(styledname),
                                           Rails.application.routes.url_helpers.edit_user_path(id)
  end

  def bitedit
    ApplicationController.render partial: 'users/togglebuttoncontainer', locals: { user: self }
  end

  include Codegen

  def add_friends
    sn = Event.shortname(CURRENT_EVENT_ID)
    daytix = 5 - friendtickets.event(CURRENT_EVENT_ID).where(desc: "#{sn} Day ticket").count
    weektix = 2 - friendtickets.event(CURRENT_EVENT_ID).where(desc: "#{sn} Weekend ticket").count

    daytix.times do
      Friendticket.new(user: self, event_id: CURRENT_EVENT_ID, code: gen_code, desc: "#{sn} Day ticket").save!
    end
    weektix.times do
      Friendticket.new(user: self, event_id: CURRENT_EVENT_ID, code: gen_code, desc: "#{sn} Weekend ticket").save!
    end
  end

  def add_pms
    p = Pmscode.all.where(event_id: CURRENT_EVENT_ID, user: nil).first
    return unless p

    p.user_id = id
    p.save
  end

  def add_orgextra
    sn = Event.shortname(CURRENT_EVENT_ID)
    Friendticket.new(user: self, event_id: CURRENT_EVENT_ID, code: gen_code, desc: "#{sn} Org weekend ticket").save!
  end

  before_save :sync_to_ldap
  after_save :check_codes
  def check_codes
    # add_friends if eventorg? && friendtickets.event(CURRENT_EVENT_ID).count < 2
    add_pms if eventorg? && pmscodes.event(CURRENT_EVENT_ID).empty?
    # add_orgextra if friendtickets.event(CURRENT_EVENT_ID).count == 0

    return unless !eventorg? && friendtickets.event(CURRENT_EVENT_ID).count > 1

    friendtickets.event(CURRENT_EVENT_ID).each do |tix|
      next if tix.redeemed_at

      tix.redeemed_at = Time.zone.at(0)
      tix.redeemed_by = "Org bit lost"
      tix.save!
    end
  end

  def self.ldap_connection
    Net::LDAP.new(
      host: Rails.application.credentials.ldap_host,
      port: Rails.application.credentials.ldap_port,
      auth: {
        method: :simple,
        username: Rails.application.credentials.ldap_user,
        password: Rails.application.credentials.ldap_pass
      }
      # encryption: { method: :simple_tls }, # , tls_options: OpenSSL::SSL::SSLContext::DEFAULT_PARAMS },
    )
  end

  def self.try_ldap_auth(user, pass)
    dn = nil
    ldap = User.ldap_connection

    ldap.search(base: "ou=people,dc=assembly,dc=org",
                filter: "(&(objectClass=inetOrgPerson)(cn=#{user}))") { |e| dn = e.dn }
    return false unless dn

    ldap.auth(dn, pass)

    if ldap.bind
      dn
    else
      false
    end
  end

  def ldapgroups
    groups.split(";").map { |x| "cn=#{x},ou=groups,dc=assembly,dc=org" }
  end

  def create_ldap_user(username, password)
    ldap = User.ldap_connection
    ldap.bind
    safe_username = username.gsub(/Ä/, 'A').gsub(/Ö/, 'Ö').gsub(/ä/, 'a').gsub(/ö/, 'o').gsub(/[^A-Za-z0-9_-]/, '')
    hashed_password = Net::LDAP::Password.generate(:ssha, password)

    self.dn = "cn=#{safe_username},ou=people,dc=assembly,dc=org"
    ldap.add(
      dn: dn,
      attributes: {
        objectClass: %w[inetOrgPerson asmorgEventOrganizer],
        cn: safe_username,
        sn: 'new',
        userPassword: hashed_password
      }
    )
    ldap.get_operation_result
  end

  def sync_to_ldap(force: false)
    ldap = User.ldap_connection
    ldap.bind
    ldap.replace_attribute dn, :asmorgEventParticipation, events.map(&:code)

    return unless force || changed?

    ldap.replace_attribute dn, :givenName, firstname if force || changed.include?('firstname')
    ldap.replace_attribute dn, :sn, lastname if force || changed.include?('lastname')
    ldap.replace_attribute dn, :asmorgNickName, nickname if force || changed.include?('nickname')
    ldap.replace_attribute dn, :displayName, displayname if force || changed.include?('displayname')
    ldap.replace_attribute dn, :departmentNumber, team if force || changed.include?('team')
    ldap.replace_attribute dn, :telephoneNumber, phone if force || changed.include?('phone')
    ldap.replace_attribute dn, :asmorgBirthday, birthday.iso8601 if birthday && (force || changed.include?('birthday'))
    if organizerbegin && (force || changed.include?('organizerbegin'))
      ldap.replace_attribute dn, :asmorgOrganizerBeginDate, organizerbegin.iso8601
    end
    ldap.replace_attribute dn, :asmorgTshirtsize, tshirtsize if force || changed.include?('tshirtsize')
    ldap.replace_attribute dn, :asmorgDietaryRequirement, diet.split(";") if diet && (force || changed.include?('diet'))
    ldap.replace_attribute dn, :asmorgDietaryRequirementNotes, dietnotes if force || changed.include?('dietnotes')
    ldap.replace_attribute dn, :street, street if force || changed.include?('street')
    ldap.replace_attribute dn, :postalCode, postalcode if force || changed.include?('postalcode')
    ldap.replace_attribute dn, :postalAddress, postaladdress if force || changed.include?('postaladdress')
    ldap.replace_attribute dn, :title, title if force || changed.include?('title')
    ldap.replace_attribute dn, :mail, email if force || changed.include?('email')
    ldap.replace_attribute dn, :jpegPhoto, photo if force || changed.include?('photo')

    # LDAP group memberships must come from group side, not from user side
    # ldap.replace_attribute dn, :memberOf, ldapgroups
    User.syncallgroups if force || changed.include?('groups')
  end

  # Free text field, can be modified
  def self.tshirtsizes
    %w[ ---
        XXS XS S M L XL XXL XXXL XXXXL
        LadyXXS LadyXS LadyS LadyM LadyL LadyXL LadyXXL LadyXXXL LadyXXXXL LadyXXXXXL]
  end

  # Coded as numbers, Do not modify or other systems break!
  def self.dietaryoptions
    cc = 0
    [
      "No lactose - laktoositon",
      "No milk - ei maitoa",
      "No peas - ei herneitä",
      "No tomato - ei tomaattia",
      "No citrus - ei sitrushedelmiä (kiivi, ananas, sitruuna, yms)",
      "No mushrooms - ei sieniä",
      "No shellfish - ei äyriäisiä",
      "No fish - ei kalaa",
      "No beans - ei papuja",
      "No nuts - ei pähkinöitä",
      "No apple - ei omenaa",
      "No carrot - ei porkkanaa",
      "No banana - ei banaania",
      "No eggs - ei kananmunaa",
      "No soy - ei soijaa",
      "No bell peppers - ei paprikaa",
      "No grains/gluten free - viljaton/gluteeniton",
      "No meat - ei lihaa"
    ].to_h do |o|
      cc += 1
      [cc, o]
    end
  end

  def dietoptions
    return "" unless diet

    diet.split(";")
  end

  def dietlist
    return [] unless diet

    diet.split(";").map { |x| User.dietaryoptions[x.to_i] }
  end

  def shortgroups
    return [] unless groups

    groups.split(";").map { |x| x.gsub(/,.*/, '') }.delete_if { |x| x == 'confluence-users' }
  end

  def self.allgroups
    [
      # Mapped to xwiki admin & users
      "confluence-administrators",
      "confluence-users",

      # General admin group
      "people-managers",

      # Access to lost&found & infolog
      "infolog",

      "marcom",
      "visitor-experience",

      "buildcrew,ou=crews",
      "compocrew,ou=crews",
      "digital-lifestyle,ou=crews",
      "esportscrew,ou=crews",
      "GamingCrew,ou=crews",
      "infocrew,ou=crews",
      "ivocrew,ou=crews",

app/controllers/users_controller.rb
require 'mimemagic'

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy toggle_event]
  skip_before_action :require_login, only: %i[mailinglists new create]

  # GET /Users or /contacts.json
  def index
    if current_user.admin?
      @users = User.nophoto.order('dn').includes(:events)
    else
      redirect_to edit_user_path(current_user)
    end

    @teams = []
    User.active.all.each do |user|
      next unless user.in_current_event?
      next unless user.team

      @teams << user.team unless @teams.include?(user.team)
    end
    @events = Event.recent.order('id desc').all.map(&:shortname)

    @fullwidth = true

    return unless request.xhr?

    render json: @users,
           only: %i[dn state displayname firstname lastname nickname team title email tshirtsize phone birthday
                    organizerbegin],
           methods: %i[namelink lastevent allevents shortgroups bitedit]
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    invite = Invite.find_by(token: params[:token])
    @verified = invite && invite.usedby.nil?
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  def photo
    user = User.find(params[:id])
    unless user.photo
      render status: :not_found, plain: 'Not found'
      return
    end
    mimetype = MimeMagic.by_magic(user.photo)
    response['Cache-Control'] = 'public, max-age=604800'
    send_data user.photo, type: mimetype, disposition: 'inline'
  end

  # POST /users or /users.json
  def create
    invite = Invite.find_by(token: params[:token])
    @user = User.new(state: 1, organizerbegin: Time.zone.today, displayname: '',
                     events: [Event.find(CURRENT_EVENT_ID)], groups: 'confluence-users')
    ret = @user.create_ldap_user(params[:username], params[:password])

    if !ret || ret[:code] != 0
      @user.errors.add(:base, "User creation failed: #{ret[:message]}")
      render :new, status: :unprocessable_entity
      return
    end

    respond_to do |format|
      if @user.save
        # Log in automatically
        invite.usedby = @user
        invite.save!

        session[:user] = @user.id
        format.html { redirect_to edit_user_path(@user), notice: "User account created. Please fill in details." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    unless current_user == @user || current_user.admin?
      render text: "No permissions"
      return
    end

    # params[:user][:diet] = params[:user][:diet].reject(&:empty?).join(";") if params[:user][:diet].is_a? Array

    params[:user][:photo] = params[:user][:photo].read if params[:user][:photo]
    params[:user][:diet] = params[:user][:diet].keys.join(";") if params[:user][:diet]

    if current_user.admin?
      if params[:user][:events]
        events = Event.where(code: params[:user][:events].keys)
        @user.events = events
        @user.save
      end
      params[:user][:groups] = params[:user][:groups].keys.join(";") if params[:user][:groups]

    end

    respond_to do |format|
      if @user.update(users_params)

        # Disable/enable edits groups so it must happen after .update (since it also updates groups)
        if @current_user.admin?
          @user.disable if params[:commit] == 'Disable user'
          @user.enable if params[:commit] == 'Enable user'
          @user.save
        end

        @user.sync_to_ldap(force: true)
        notice = 'User was successfully updated.'
        if @user.created_at < 15.minutes.ago
          notice = 'Thank you for filling in the details. Please contact you recruiter for user account verification.'
        end
        format.html { redirect_to user_url(@user), notice: notice }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    unless current_user.admin?
      render text: "No permissions"
      return
    end
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_event
    @user.events.delete(Event.current) if params[:remove] == 'true'
    @user.events << Event.current if params[:add] == 'true'
    @user.save
  end

  def mailinglists
    unless request.headers[:authorization] == Rails.application.credentials.mailinglist_auth
      render plain: "Invalid auth", status: :unauthorized
      return
    end

    @lists = {}
    listname_exceptions = {
      "core" => "ydin",
      "livecrew" => "live-crew",
      "livecrew-core" => "live-core",
      "webcrew" => "web"
    }

    User.active.nophoto.find_each do |user|
      next unless user.email

      @lists['organizers'] ||= []
      @lists['organizers'] << user.email

      user.groups.split(';').each do |group|
        next if %w[confluence-users marcom].include?(group)

        group.gsub!(/,.*/, "")
        group.gsub!(/[^A-Za-z0-9-]/, "")
        group = listname_exceptions[group] if listname_exceptions[group]
        @lists[group] ||= []
        @lists[group] << user.email
      end
    end
    render plain: @lists.map { |l, v| v.map { |e| "#{l},#{e}" } }.flatten.join("\n")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    params[:id] = current_user.id if params[:id] == 'self'
    @user = User.find(params[:id])
    return if current_user == @user || current_user.admin?

    redirect_to users_url,
                notice: "No permissions"
  end

  # Only allow a list of trusted parameters through.
  def users_params
    allowed = %i[
      firstname lastname displayname nickname phone birthday organizerbegin tshirtsize diet dietnotes street postalcode postaladdress email photo
    ]
    allowed += %i[events groups team title] if current_user.admin?
    params.require(:user).permit(allowed)
  end
end

app/views/users/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Title:</strong>
    <%= contact.title %>
  </p>

  <p>
    <strong>User:</strong>
    <%= contact.user_id %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

</div>

app/views/users/_togglebutton.html.erb
<%=user.lastevent %>&nbsp;
<% if user.in_current_event? %>
<%=button_to raw('<i class="bi bi-x-lg" aria-hidden="true"></i>'), Rails.application.routes.url_helpers.toggle_event_user_path(user, remove:true), remote: true, class: 'btn btn-sm btn-danger', form_class: 'inline' %>
<% else %>
<%=button_to '+' + Event.revshortname(CURRENT_EVENT), Rails.application.routes.url_helpers.toggle_event_user_path(user, add:true), remote: true, class: 'btn btn-sm btn-primary', form_class: 'inline' %>
<% end %>

app/views/users/_togglebuttoncontainer.html.erb
<div id="togglebutton_<%=user.id%>">
<%=render partial: 'users/togglebutton', locals: { user: user } %>
</div>

app/views/users/edit.html.erb
<h1>Edit user details</h1>

<%= render "form", user: @user %>

app/views/users/export.vcf.erb
<%@contacts.each do |c| %>
BEGIN:VCARD
VERSION:4.0
<% if c.user %>
FN:<%=c.user.displayname%> (Assembly <%=c.title%>)
N:<%=c.user.lastname%>;<%=c.user.firstname%>;;;
TEL;TYPE=cell:<%=c.user.phone || c.phone%>
NICKNAME:<%=c.user.nickname%>
<% else %>
FN:Assembly <%=c.title%>
TEL;TYPE=cell:<%=c.phone%>
NICKNAME:<%=c.user.nickname%>
ORG:Assembly
<% end %>
END:VCARD
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>


<div class="toolbar container" id="toolbar">
    <div class="row">
        <div class="col">
            <label for="inactive">
                Inactive:
            </label>
            <select class="form-select filter" style="display: inline-block" id="inactive">
                <option value="hide" selected>Hide</option>
                <option value="all">Show all</option>
                <option value="only">Only</option>
            </select>
        </div>
        <div class="col">
            <label for="team">
                Team (this event):
            </label>
            <select class="form-select filter" style="display: inline-block" id="team">
                <option value="-">-</option>
                <%@teams.sort.each do |team|%>
                <option value="<%=team%>"><%=team%></option>
                <% end %>
            </select>
        </div>
        <div class="col">
            <label for="event">
                Event
            </label>
            <select class="form-select filter" style="display: inline-block" id="event">
                <option value="-">-</option>
                <%@events.each do |event|%>
                <option value="<%=event%>"><%=event%></option>
                <% end %>
            </select>
        </div>
        <!--<button id="foo" class="btn btn-primary">Click me</button>-->
    </div>
</div>

<div id="users">

    <table class="table table-striped table-bordered table-hover table-condensed" id="usertable" data-toggle="table" data-search="true" data-show-columns="true" data-url="<%=users_url%>" data-toolbar="#toolbar" data-show-export="true" data-toolbar="toolbar" data-editable-url="<%=users_url%>" data-id-field="dn" data-editable-emptytext="None">
        <thead>
            <tr>
                <th data-sortable="true" data-field="dn" data-visible="false">DN</th>
                <th data-sortable="true" data-field="namelink">Preferred name</th>
                <th data-sortable="true" data-field="firstname" data-visible="false">First name</th>
                <th data-sortable="true" data-field="lastname" data-visible="false">Last name</th>
                <th data-sortable="true" data-field="nickname">Nick</th>
                <th data-sortable="true" data-field="title" data-editable="true">Title</th>
                <th data-sortable="true" data-field="team" data-editable="true">Team</th>
                <th data-sortable="true" data-field="email" data-visible="false">Email</th>
                <!--<th data-sortable="true" data-field="hetu" data-visible="false">Hetu</th>-->
                <!--<th data-sortable="true" data-field="photook">Photo?</th>-->
                <th data-sortable="true" data-field="tshirtsize">T-shirt</th>
                <!--<th data-sortable="true" data-field="orgbit">Org?</th>-->
                <th data-sortable="true" data-field="bitedit">Event bit</th>
                <th data-sortable="true" data-field="shortgroups">Groups</th>
                <th data-sortable="true" data-field="allevents" data-visible="false">All events</th>
                <th data-sortable="true" data-field="phone" data-visible="false">Phone</th>
                <th data-sortable="true" data-field="birthday" data-visible="false">Birthday</th>
                <th data-sortable="true" data-field="organizerbegin" data-visible="false">Org.begin</th>
                <th data-sortable="true" data-field="address" data-visible="false">Address</th>
                <th data-sortable="true" data-field="state" data-visible="false">State</th>
            </tr>
        </thead>
    </table>
</div>

<script>
    function filterRow(row, filters) {
        inactive = $('#inactive').val();
        if (inactive == 'hide' && row['state'] != 1) {
            return false;
        }
        if (inactive == 'only' && row['state'] != 0 && row['state'] != 2) {
            return false;
        }

        team = $('#team').val();
        if (team != '-' && row['team'] != team) {
            return false;
        }

        event = $('#event').val();
        if (event != '-' && row['allevents'].indexOf(event) == -1) {
            return false;
        }
        return true;
    }

    function filterData() {
        $('#usertable').bootstrapTable('filterBy', {}, {
            filterAlgorithm: filterRow
        });
    }

    $(function() {
        $('.filter').change(function(ev) {
            filterData();
        });

        $('#usertable').bootstrapTable({
            onLoadSuccess: function(data) {
                $('#usertable').bootstrapTable('filterBy', {
                    state: 1
                });
            }
        })
    });
</script>


<%= link_to "New contact", new_contact_path %> |
<%= link_to "Export", export_contacts_path %>

app/views/users/new.html.erb
<h1>Welcome to Assembly</h1>

<% if @verified %>
<p>
    In order to get started with Assembly we need to create an user account for you and get some basic details.
</p>
<p>
    Please enter username and password you would like to use with Assembly
</p>

<% @user.errors.each do |error| %>
<div class="alert alert-danger" role="alert">
    <%= error.full_message %>
</div>
<% end %>

<%= form_tag users_path do %>
<%=hidden_field_tag :token, params[:token] %>

<div class="row gy-2">
    <div class="col-4">
        <%= label_tag :username, 'Username', class: 'form-label' %>
        <%= text_field_tag :username, '', class: 'form-control' %>
    </div>
    <div class="col-4">
        <%= label_tag :password, 'Password', class: 'form-label' %>
        <%= password_field_tag :password, '', class: 'form-control' %>
    </div>
</div>

<div style="padding-top: 1rem">
    <%= submit_tag 'Create', class: 'btn btn-primary' %>
</div>
<% end %>
<% else %>
<p>
    The token code you gave is invalid. Please contact your recruiter again for new token.
</p>
<%=form_tag new_user_path, method: :get do %>
<div>
    <%= label_tag :token, 'Token', class: 'form-label' %>
    <%= text_field_tag :token, '', class: 'form-control' %>
</div>
<%= submit_tag 'Try again', class: 'btn btn-primary' %>
<% end %>
<% end %>

app/views/users/show.html.erb
User: <%=@user.displayname%>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to user list", users_path %>
</div>

app/views/users/toggle_event.js.erb
$('#togglebutton_<%=@user.id%>').html("<%= escape_javascript(
render partial: 'togglebutton', locals: { user: @user }
) %>");