config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invites
  resources :info_logs
  resources :lost_items
  get 'peliluola', as: 'afterparty', action: 'index', controller: 'afterparty'
  post 'peliluola/signup', as: 'signup_afterparty', controller: 'afterparty', action: 'signup'

  resources :contacts do
    collection do
      get 'export'
    end
  end

  resources :users do
    collection do
      get 'mailinglists'
    end
    member do
      get 'photo'
      post 'toggle_event'
    end
  end

  get "sessions/create", as: "login"
  post "sessions/auth", as: "auth"
  get "sessions/logout", as: "logout"
  post "sessions/logout"
  get 'oidc/authenticator/callback', to: 'sessions#sso'

  # a-umlaut in querystring just fails...
  get "friendtickets/conflulist"
  # so putting it in path works...
  get "friendtickets/conflulist/:cn", controller: 'friendtickets', action: 'conflulist'

  get "friendtickets/search", as: "search_friendtickets"
  post "friendtickets/search"

  get "friendtickets/own"
  post "friendtickets/own"

  get "friendtickets/edit"
  patch "friendtickets/:id", controller: 'friendtickets', as: 'friendticket', action: 'update'

  get "friendtickets/stats"

  resources :events do
    member do
      get 'stats'
      get 'organizers'
      get 'allergies'
    end
  end

  root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :eventparticipations, dependent: :destroy
  has_many :eventparticipationmetum, dependent: :destroy
  has_many :users, through: :eventparticipations
  has_many :friendtickets, dependent: :destroy
  has_many :lost_items
  has_many :info_logs

  scope :recent, -> { where("code::integer > :c and name not like '%afterparty'", c: (Time.current.year - 5) * 100) }

  # TODO: Better sort
  def <=>(other)
    id <=> other.id
  end

  def shortname
    Event.shortname(code)
  end

  def afterparty?
    name.downcase.include? 'afterparty'
  end

  def self.current
    Event.find(CURRENT_EVENT_ID)
  end

  def self.revshortname(eventid)
    sn = Event.shortname(eventid)
    sn[1..2] + sn[0]
  end

  def self.shortname(eventid)
    if eventid.to_i < 100
      event = Event.find(eventid)
      code = event.code
    else
      code = eventid
    end
    yr = (code.to_i / 100) % 100
    ev = code.to_i % 100
    case ev
    when 1
      "W#{yr}"
    when 2
      "S#{yr}"
    when 5
      "G#{yr}"
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy organizers stats allergies]
  before_action :require_admin

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show; end
  def organizers; end

  def allergies
    @allergies = {}
    @dietnotes = []
    @event.users.each do |u|
      u.dietlist.each do |d|
        @allergies[d] ||= 0
        @allergies[d] += 1
      end
      @dietnotes << u.dietnotes if u.dietnotes.present?
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def stats
    @groups = {}
    @postaddr = {}
    @postcode = {}
    @ages = {}

    totalage = 0
    agecount = 0

    @event.users.each do |u|
      u.shortgroups.each do |g|
        next if g == 'confluence-users'

        @groups[g] ||= 0
        @groups[g] += 1
      end

      if u.birthday
        age = ((Time.zone.today - u.birthday) / 365.2524).to_i
        @ages[age] ||= 0
        @ages[age] += 1
        totalage += age
        agecount += 1
      end

      if u.postaladdress
        @postaddr[u.postaladdress] ||= 0
        @postaddr[u.postaladdress] += 1
      end

      next unless u.postalcode

      code = u.postalcode[0..2] + 'xx'
      @postcode[code] ||= 0
      @postcode[code] += 1
    end
    @avgage = totalage.to_f / agecount
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:code, :name)
  end

  def require_admin
    return if current_user.admin?

    render text: "No permissions"
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/allergies.html.erb
<h1>Food allergies in <%=@event.name%></h1>

<h2>Generic allergies</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <%@allergies.sort.each do |a, c| %>
    <tr>
    <td><%=a%></td>
    <td><%=c%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>Specific notes</h2>
<ul>
<% @dietnotes.sort.each do |d| %>
    <li><%=d%></li>
<% end %>
</ul>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.sort.reverse.each do |event| %>
      <tr class="<%=event.id == CURRENT_EVENT_ID ? 'table-warning' : ''%>">
        <td><%= event.code %></td>
        <td><%= event.name %></td>
        <td><%= link_to 'Allergies', allergies_event_path(event) %></td>
        <td><%= link_to 'Stats', stats_event_path(event) %></td>
        <td><%= link_to 'Organizers', organizers_event_path(event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/organizers.html.erb
<h1><%=@event.name%> organizers</h1>

<ul>
<%@event.users.sort.each do |u| %>

<li><%=u%></li>
<% end %>
</ul>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @event.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/stats.html.erb
<h1>Stats for <%=@event.name%></h1>
<!--
Select event: <%=select_tag 'event', options_from_collection_for_select(Event.all, :id, :name, @event.id), onchange: "window.location.href = '#{events_path}/'+$(this).val()+'/stats';" %>
<br />
<br />
-->

<div class="row">
<div class="col-5">
  <h2>Groups</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Group</th>
        <th>Members</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <%@groups.sort.each do |g,c|%>
        <tr>
          <td><%=g%></td>
          <td><div class="bg-primary" style="padding-left: 1ex; width: <%=c/2%>ex;"><%=c%></div></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot class="table-group-divider">
      <tr>
        <td>Total</td>
        <td><%=@event.users.count%></td>
      </tr>
    </tfoot>
  </table>
  </div>
<div class="col-2">
</div>
<div class="col-5">
  <h2>Age</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Age</th>
        <th>Count</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <%@ages.sort.each do |g,c|%>
        <tr>
          <td><%=g%></td>
          <td><div class="bg-primary" style="padding-left: 1ex; padding-right: 1ex; width: <%=c%>ex;"><%=c%></div></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot class="table-group-divider">
      <tr>
        <td>Total</td>
        <td><%=@event.users.count%></td>
      </tr>
      <tr>
        <td>Average</td>
        <td><%=@avgage.round(2)%></td>
      </tr>
    </tfoot>
  </table>
</div>
</div>

<div class="row">

<div class="col-5">
<h2>Postal addresses</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Code</th>
        <th>Users</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <%@postaddr.sort_by{|a,b| a||''}.each do |g,c|%>
        <tr>
          <td><%=g%></td>
          <td><div class="bg-primary" style="padding-left: 1ex; padding-right: 1ex; width: <%=c/2%>ex;"><%=c%></div></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="col-2">
</div>

<div class="col-5">
<h2>Postal code</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Code</th>
        <th>Users</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <%@postcode.sort_by{|a,b| a||''}.each do |g,c|%>
        <tr>
          <td><%=g%></td>
          <td><div class="bg-primary" style="padding-left: 1ex; padding-right: 1ex; width: <%=c%>ex;"><%=c%></div></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

</div>