config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invites
  resources :info_logs
  resources :lost_items
  get 'peliluola', as: 'afterparty', action: 'index', controller: 'afterparty'
  post 'peliluola/signup', as: 'signup_afterparty', controller: 'afterparty', action: 'signup'

  resources :contacts do
    collection do
      get 'export'
    end
  end

  resources :users do
    collection do
      get 'mailinglists'
    end
    member do
      get 'photo'
      post 'toggle_event'
    end
  end

  get "sessions/create", as: "login"
  post "sessions/auth", as: "auth"
  get "sessions/logout", as: "logout"
  post "sessions/logout"
  get 'oidc/authenticator/callback', to: 'sessions#sso'

  # a-umlaut in querystring just fails...
  get "friendtickets/conflulist"
  # so putting it in path works...
  get "friendtickets/conflulist/:cn", controller: 'friendtickets', action: 'conflulist'

  get "friendtickets/search", as: "search_friendtickets"
  post "friendtickets/search"

  get "friendtickets/own"
  post "friendtickets/own"

  get "friendtickets/edit"
  patch "friendtickets/:id", controller: 'friendtickets', as: 'friendticket', action: 'update'

  get "friendtickets/stats"

  resources :events do
    member do
      get 'stats'
      get 'organizers'
      get 'allergies'
    end
  end

  root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  def username=(name)
    self.user = User.where('dn ilike :dn', dn: "%#{name}%").first
  end

  def username
    return "" unless user

    user.dn
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  def export
    @contacts = Contact.all
  end

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:title, :username, :user_id, :phone)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Title:</strong>
    <%= contact.title %>
  </p>

  <p>
    <strong>User:</strong>
    <%= contact.user_id %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/export.vcf.erb
<%@contacts.each do |c| %>
BEGIN:VCARD
VERSION:4.0
<% if c.user %>
FN:<%=c.user.displayname%> (Assembly <%=c.title%>)
N:<%=c.user.lastname%>;<%=c.user.firstname%>;;;
TEL;TYPE=cell:<%=c.user.phone || c.phone%>
NICKNAME:<%=c.user.nickname%>
<% else %>
FN:Assembly <%=c.title%>
TEL;TYPE=cell:<%=c.phone%>
NICKNAME:<%=c.user.nickname%>
ORG:Assembly
<% end %>
END:VCARD
<% end %>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %> | 
<%= link_to "Export", export_contacts_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>