config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invites
  resources :info_logs
  resources :lost_items
  get 'peliluola', as: 'afterparty', action: 'index', controller: 'afterparty'
  post 'peliluola/signup', as: 'signup_afterparty', controller: 'afterparty', action: 'signup'

  resources :contacts do
    collection do
      get 'export'
    end
  end

  resources :users do
    collection do
      get 'mailinglists'
    end
    member do
      get 'photo'
      post 'toggle_event'
    end
  end

  get "sessions/create", as: "login"
  post "sessions/auth", as: "auth"
  get "sessions/logout", as: "logout"
  post "sessions/logout"
  get 'oidc/authenticator/callback', to: 'sessions#sso'

  # a-umlaut in querystring just fails...
  get "friendtickets/conflulist"
  # so putting it in path works...
  get "friendtickets/conflulist/:cn", controller: 'friendtickets', action: 'conflulist'

  get "friendtickets/search", as: "search_friendtickets"
  post "friendtickets/search"

  get "friendtickets/own"
  post "friendtickets/own"

  get "friendtickets/edit"
  patch "friendtickets/:id", controller: 'friendtickets', as: 'friendticket', action: 'update'

  get "friendtickets/stats"

  resources :events do
    member do
      get 'stats'
      get 'organizers'
      get 'allergies'
    end
  end

  root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
    <title>Ruttu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag "application" %>
</head>

<body>

    <% if logged_in? %>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <div class="col-md-1 mb-2 mb-md-0">
            </div>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><%=link_to 'Edit own profile', edit_user_path(current_user), class: 'nav-link px-2'%></li>
                <% if false %>
                <li><%=link_to 'Friend tickets', friendtickets_own_path, class: 'nav-link px-2'%></li>
                <% if current_user&.access_friendtickets? %>
                <li><%=link_to 'Redeem tickets', search_friendtickets_path, class: 'nav-link px-2'%></li>
                <% end %>
                <% end %>

                <% if Time.now > Time.parse('2025-02-24 12:00:00 EEST') %>
                <li><%=link_to 'Afterparty', afterparty_path, class: 'nav-link px-2'%></li>
                <% end %>
                <% if current_user&.admin? %>
                <li><%=link_to 'Edit users', users_path, class: 'nav-link px-2'%></li>
                <li><%=link_to 'Invites', invites_path, class: 'nav-link px-2'%></li>
                <li><%=link_to 'Events', events_path, class: 'nav-link px-2'%></li>
                <% end %>
                <% if current_user&.access_infolog? %>
                <li><%=link_to 'Lost&Found', lost_items_path, class: 'nav-link px-2'%></li>
                <li><%=link_to 'Info logs', info_logs_path, class: 'nav-link px-2'%></li>
                <% end %>
            </ul>

            <div class="col-md-2 text-end">
                <%= button_to 'Logout', logout_path, { class: 'btn btn-outline-primary me-2', method: 'GET' } %>
            </div>
        </header>
    </div>
    <% end %>

    <div class="container<%=@fullwidth?'-fluid':''%>" style="padding-top: 20px">
        <% if flash[:notice] %>
        <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
        <% end %>
        <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
        <% end %>

        <%= yield %>

    </div><!-- /.container -->

</body>

</html>